services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama 

  nginx_ollama:
    build: ./nginx
    depends_on:
      - ollama
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

volumes:
  ollama:

#Use this configuration in production with nginx-proxy container
networks:
  default:
    external: true
    name: nginx-proxy
    